name: Docs build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Docs Build
        run: pnpm run docs:build
      - name: Delopy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs-dist
          target_branch: gh-pages
          personal_token: ${{ secrets.ACCESS_TOKEN }}
